import { v4 as uuidv4 } from 'uuid';

export default [
    {
        id: uuidv4(),
        username: 'Adedeji',
        email: 'adedeji@lendsqr.com',
        telephone: '08010000000',
        status: 'Inactive',
    },
    {
        id: uuidv4(),
        username: 'Debby Ogana',
        email: 'debby@irorun.com',
        telephone: '08010000000',
        status: 'Pending',
    },
    {
        id: uuidv4(),
        username: 'Tosin Dokunmu',
        email: 'tosin@lendsqr.com',
        telephone: '08010000000',
        status: 'Blacklisted',
    },
    {
        id: uuidv4(),
        username: 'Grace Effion',
        email: 'grace@lendsqr.com',
        telephone: '08010000000',
        status: 'Pending',
    },
    {
        id: uuidv4(),
        username: 'Tosin Dokunmu',
        email: 'tosin@lendsqr.com',
        telephone: '08010000000',
        status: 'Active',
    },
    {
        id: uuidv4(),
        username: 'Grace Effion',
        email: 'grace@lendsqr.com',
        telephone: '08010000000',
        status: 'Active',
    },
    {
        id: uuidv4(),
        username: 'Tosin Dokunmu',
        email: 'tosin@lendsqr.com',
        telephone: '08010000000',
        status: 'Blacklisted',
    },
    {
        id: uuidv4(),
        username: 'Grace Effion',
        email: 'grace@lendsqr.com',
        telephone: '08010000000',
        status: 'Inactive',
    },
    {
        id: uuidv4(),
        username: 'Adedeji',
        email: 'adedeji@lendsqr.com',
        telephone: '08010000000',
        status: 'Inactive',
    },
    {
        id: uuidv4(),
        username: 'Debby Ogana',
        email: 'debby@irorun.com',
        telephone: '08010000000',
        status: 'Pending',
    },
    {
        id: uuidv4(),
        username: 'Tosin Dokunmu',
        email: 'tosin@lendsqr.com',
        telephone: '08010000000',
        status: 'Blacklisted',
    },
    {
        id: uuidv4(),
        username: 'Grace Effion',
        email: 'grace@lendsqr.com',
        telephone: '08010000000',
        status: 'Pending',
    },
    {
        id: uuidv4(),
        username: 'Tosin Dokunmu',
        email: 'tosin@lendsqr.com',
        telephone: '08010000000',
        status: 'Active',
    },
    {
        id: uuidv4(),
        username: 'Grace Effion',
        email: 'grace@lendsqr.com',
        telephone: '08010000000',
        status: 'Active',
    },
    {
        id: uuidv4(),
        username: 'Tosin Dokunmu',
        email: 'tosin@lendsqr.com',
        telephone: '08010000000',
        status: 'Blacklisted',
    },
    {
        id: uuidv4(),
        username: 'Grace Effion',
        email: 'grace@lendsqr.com',
        telephone: '08010000000',
        status: 'Inactive',
    },
]